# Legacy makefile for Linux
#
# Not support for husky build enviroment (makefile.cfg)

CC=gcc
OBJ=.o
RM=rm
EXE=
CFLAGS=-O3 -I../h -I../.. -DUNIX
LFLAGS=-s -L../../fidoconf -L../../smapi
LIBS= -lfidoconfiglnx -lsmapilnx

%$(OBJ): $(SRC_DIR)%.c
	$(CC) $(CFLAGS) -c $<

include makefile.inc

all: commonprogs

default: all

clean: commonclean

commondistclean: commonclean commondistclean
