# Legacy makefile for Linux
#
# Not support for husky build enviroment (makefile.cfg)

CC=gcc
_OBJ=.o
RM=rm
EXE=
CFLAGS=-O2 -I../h -I../../fidoconf -DUNIX
LFLAGS=-s -L../../fidoconf/make
LIBS= -lfidoconfigqnx
SRC_DIR=../src/

%$(_OBJ): $(SRC_DIR)%.c
	$(CC) $(CFLAGS) -c $<

include makefile.inc

all: commonprogs

default: all

clean: commonclean

commondistclean: commonclean commondistclean
