# Legacy makefile for Linux
#
# Not support for husky build enviroment (makefile.cfg)

CC=gcc
OBJ=.o
RM=rm
EXE=
SRC_DIR=../src/
CFLAGS=-O3 -I../h -I../.. -DUNIX
LFLAGS=-s -L../../fidoconf -L../../smapi
LIBS= -lfidoconfiglnx -lsmapilnx

include makefile.inc

all: commonprogs

%$(OBJ): $(SRC_DIR)%.c
		$(CC) $(CFLAGS) -c $<

default: all

clean: commonclean

distclean: commonclean commondistclean
