# Legacy makefile for MinGW compiler
#
# This builds a Win32 executable the requires CRTDLL.DLL


CC=i386-mingw32-gcc
OBJ=.o
EXE=.exe
RM=del
CFLAGS=-O3 -I../.. -DNT -DWINNT
LFLAGS=-O3 -L../../fidoconf
LIBS=../../fidoconf/libfidoconfigmgw.a ../../smapi/libsmapimgw.a

.SUFFIXES:
.SUFFIXES: .c .o .exe

.c.o:
	$(CC) $(CFLAGS) -c $<

include makefile.inc

all: commonprogs

default: all

clean:
	-$(RM) *$(OBJ)

distclean: clean commondistclean
